# Buckaruby RuboCop configuration

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 8

Style/AccessorMethodName:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: false
