# Buckaruby RuboCop configuration

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'


Layout/LineLength:
  Enabled: false


Metrics/AbcSize:
  Max: 27

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10


RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 17

RSpec/MultipleExpectations:
  Max: 12

RSpec/NestedGroups:
  Max: 4


Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false
