# Buckaruby RuboCop configuration

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 27

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false
