# Buckaruby RuboCop configuration

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true


# We target 2.3, but still want to support 2.0.
Gemspec/RequiredRubyVersion:
  Enabled: false


Layout/LineLength:
  Enabled: false


Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true


Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 9


Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false


RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 17

RSpec/MultipleExpectations:
  Max: 12

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4


Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
